#!/usr/bin/env bash

FZFARGS='ctrl-d:execute-silent(echo {} | cliphist delete)+reload-sync(cliphist list),ctrl-f:execute(cliphist wipe)+reload-sync(cliphist list)'

case "$1" in
preview)
    row="$2"
    if echo "$row" | grep -vqP '^\d+\t\[\[ binary data .* \]\]'; then
        echo "$row" | cliphist decode
    else
        echo "$row" | cliphist decode | chafa -f sixel -s "${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}"
    fi
    ;;

*)
    id=$(cliphist list | fzf -d $'\t' --bind "$FZFARGS"  --with-nth 2 --height=100% --layout=reverse --border --preview  "$(realpath "$0") preview {}" --list-border --list-label="Clipboard")
    test -z "$id" && exit

    cliphist decode <<<"$id" | wl-copy
    ;;

esac
