bind=SUPER,F8,spawn,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bind=SUPER,F9,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
mousebind=SUPER,btn_side,spawn,playerctl previous
mousebind=SUPER,btn_extra,spawn,playerctl next
bind=SUPER,F10,spawn,playerctl pause

bind=NONE,Print,spawn,wayfreeze --hide-cursor --after-freeze-cmd 'grim -g "$(slurp)" - | wl-copy; killall wayfreeze'

bind=SUPER,d,spawn,rofi -show drun

bind=SUPER,v,spawn,foot -a menu clipboard
bind=SUPER,space,spawn,foot -a hmenu menu.holder
