shadowscolor = 0x14141280
rootcolor = 0x2D2B29FF
bordercolor = 0x817F71FF
dropcolor = 0x14141280
splitcolor = 0x594B46FF
focuscolor = 0x706632FF
maximizescreencolor = 0xB8AA58FF
urgentcolor = 0xD9D3AEFF
scratchpadcolor = 0x706E63FF
globalcolor = 0x4E4922FF
overlaycolor = 0x684B46FF
