# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x1c1d21ff
rootcolor = 0x1c1d21ff
bordercolor = 0x676770ff
dropcolor = 0x989bb380
splitcolor = 0x978fa3ff
focuscolor = 0x989bb3ff
maximizescreencolor = 0x918da5ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0x978fa3ff
globalcolor = 0x414358ff
overlaycolor = 0x393649ff
