shadowscolor = 0x{{ background | strip}}{{ 50 | alpha_hexa}}
rootcolor = 0x{{ color8 | strip }}{{ 100 | alpha_hexa}}
bordercolor = 0x{{ color6 | strip }}{{ 100 | alpha_hexa}}
dropcolor = 0x{{ background | strip }}{{ 50 | alpha_hexa}}
splitcolor = 0x{{ color1 | strip }}{{ 100 | alpha_hexa}}
focuscolor = 0x{{ color5 | saturate(0.5) | strip }}{{ 100 | alpha_hexa}}
maximizescreencolor = 0x{{ color5 | lighten(0.5) | saturate(0.5) | strip}}{{ 100 | alpha_hexa}}
urgentcolor = 0x{{ foreground | strip }}{{ 100 | alpha_hexa}}
scratchpadcolor = 0x{{ color5 | strip }}{{ 100 | alpha_hexa}}
globalcolor = 0x{{ color5 | darken(0.3) | saturate(0.5) | strip }}{{ 100 | alpha_hexa}}
overlaycolor = 0x{{ color2 | strip }}{{ 100 | alpha_hexa}}
