# colors for foot terminal
# You can use this template by adding the following to wallust.toml:
# foot = { template = "foot.ini", target = "~/.config/foot/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/foot/colors.ini


[colors-dark]
background=141412
foreground=D9D3AE

# Normal/regular colors (color palette 0-7)
regular0=181715  # black
regular1=594B46  # red
regular2=684B46  # green
regular3=5D574B  # yellow
regular4=636358  # blue
regular5=706E63  # magenta
regular6=817F71  # cyan
regular7=D9D3AE  # white

# Bright colors (color palette 8-15)
bright0=2D2B29   # bright black
bright1=715850   # bright red
bright2=8C5850   # bright green
bright3=786E58   # bright yellow
bright4=848370   # bright blue
bright5=848068   # bright magenta
bright6=A49E7F   # bright cyan
bright7=D9D3AE   # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>
